### ISSUE TITLE
📢 sfdx-hardis v5 has been released !

### ISSUE THREAD

**Issue by nvuillam** [hardisgroupcom/sfdx-hardis#795]
See release notes !

https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v5.0.1

If you see any issue, please create them and post a comment here :)

**Comment by alesremta-ext43767** [comment]
Hi @nvuillam . I noticed a problem with purging flows.. and then noticed it may be with all commands? https://github.com/hardisgroupcom/sfdx-hardis/issues/800 

maybe/hopefully it's just me

**Comment by alesremta-ext43767** [comment]
I also have a question about the new attribute for org:purge:flow `delete-flow-interviews`. It seems to have the same short-hand name `-f` as `allowpurgefailure`? Can I run with the delete interviews options without a prompt?

**Comment by nvuillam** [comment]
>  It seems to have the same short-hand name -f as allowpurgefailure

Good catch, it is a bug... that I just solved in v5.0.6 :)

>  Can I run with the delete interviews options without a prompt?

You could not because I forgot to handle it, but with v5.0.6 you can, please can you confirm ?

`sf hardis:org:purge:flow --no-prompt --delete-flow-interviews`

**Comment by alesremta-ext43767** [comment]
> You could not because I forgot to handle it, but with v5.0.6 you can, please can you confirm ?

Not yet @nvuillam, still having issues with https://github.com/hardisgroupcom/sfdx-hardis/issues/800

**Comment by nvuillam** [comment]
Probably a remaining tiny bug ^^ I'll check :)

**Comment by nvuillam** [comment]
@alesremta-ext43767 according to the code, it will delete prompts interview:
- if you are in CI and `--delete-flow-interviews` is sent
- if you are not in CI, and either `--delete-flow-interviews` is sent, or if the user accepts the prompt

Such behaviour such ok to me... do you confirm ? :)

**Comment by alesremta-ext43767** [comment]
> Any chance you could debug locally ? 😇
Challenge, but I'll try - though it'll take me time, this weekend is busy :-)

Though in your conditions:
1) is true, cos there were errors
2) is true, cos it's CI (so `this.deleteFlowInterviews` don't matter)
3) seems to be called with `True` from line 125

so I'd say it's number 2?

**Comment by nvuillam** [comment]
We are in v6 for a while :)

**Comment by alesremta-ext43767** [comment]
> We are in v6 for a while :)

I meant to say "tough in _our_ conditions" 😇

**Comment by nvuillam** [comment]
Do you still have an issue ?
